name: Build and Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Build & Test on .NET ${{ matrix.dotnet }}
    runs-on: windows-latest

    strategy:
      matrix:
        dotnet: ["8.0.x", "9.0.x"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Run unit tests
        run: dotnet test ./Tests/Tests.csproj --configuration Release --no-restore

      - name: Build AOT tests
        run: dotnet publish ./Tests.AOT/Tests.AOT.csproj --configuration Release -o ./Tests.AOT/publish

      - name: Run AOT test executable
        run: ./Tests.AOT/publish/Tests.AOT.exe
